### ISSUE TITLE
Some small questions for r2h function.

### ISSUE THREAD

**Issue by lnq325805524** [yangxue0827/h2rbox-mmrotate#1]
![image](https://user-images.githubusercontent.com/38419962/195927692-b7f599ff-7a71-4afc-888d-eedafec6a3d6.png)

I would like to know if the meaning in eq.5 in your paper is the same as in my figure. I found there is a gap between r2h(rbox) and gtbox. Looking forward to your reply.

**Comment by yangxue0827** [comment]
Yes, there are some categories, e.g. Plane, that can be problematic. This may also be one reason why high-precision indicators (AP75) are not good. Look forward to better solutions.

**Comment by lnq325805524** [comment]
Got it. Thanks for your reply.
