### ISSUE TITLE
数据增强

### ISSUE THREAD

**Issue by lebron-2016** [yangxue0827/h2rbox-mmrotate#10]
作者您好，请问在您的框架下可以正常使用图片的mosaic增强方法吗？还想期待一下H2RBox-v2大概什么时候发布呢？

**Comment by yangxue0827** [comment]
1. mosaic增强我之前试了一下没成功，用应该是可以的，我没有仔细调。
2. v2明天会online到arxiv，今天刚上传文章。另外，v2支持使用旋转增强了。

**Comment by lebron-2016** [comment]
> 1. mosaic增强我之前试了一下没成功，用应该是可以的，我没有仔细调。
> 2. v2明天会online到arxiv，今天刚上传文章。另外，v2支持使用旋转增强了。

喔喔好高产啊！v2的代码什么时候上传呢？

**Comment by yangxue0827** [comment]
就这几天的事了。

**Comment by yangxue0827** [comment]
H2RBox-v2: Boosting HBox-supervised Oriented Object Detection via Symmetric Learning
https://arxiv.org/abs/2304.04403

**Comment by lebron-2016** [comment]
感谢！！
