### ISSUE TITLE
What is the dotav1 annotation box file used for h2rbox?

### ISSUE THREAD

**Issue by yourbikun** [yangxue0827/h2rbox-mmrotate#16]
First of all, thank you for your open source code.
My question is very simple. As mentioned in the paper, you use horizontal boxes to predict rotation boxes, but the dotav1 dataset has both horizontal box and rotation box annotations. I also saw a preprocessing operation in the code to convert the rotation box annotation to the horizontal box annotation. So when I download and process the dataset, should I use the rotation box annotation file "labelTxt. zip" or the horizontal box annotation file "Train_Task2ugt. zip"?
I did not see any similar instructions in the readme file. I hope you can solve my confusion, thank you!

**Comment by yangxue0827** [comment]
Use rotation box annotation file "labelTxt. zip", because DOTA's horizontal box annotation is converted from the rotation box annotation as we did.

**Comment by yourbikun** [comment]
Ok, Thank you for your timely answer.

**Comment by yourbikun** [comment]
Sorry, I still have a question: Can I get a similar effect if I directly use the horizontal annotation file "Train_Task2ugt. zip", after all, they are all converted later.

**Comment by yangxue0827** [comment]
Yes, you can. You may need to modify the dataloader, please refer to DIOR dataset.

**Comment by yourbikun** [comment]
That's great, thank you.
