### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by njustczr** [yangxue0827/h2rbox-mmrotate#17]
hello，我直接用mmrotation 2.0训练h2rbox模型，直接用普通的检测标注数据就行了吗？

**Comment by yangxue0827** [comment]
DOTA和HRSC的话直接用旋转标注就行，dataloader里会自己处理成水平标注。DIOR的话就需要自己在配置文件里选用水平标注还是旋转标注。可以看所给的示例config。
