### ISSUE TITLE
code

### ISSUE THREAD

**Issue by 123456hxh** [yangxue0827/h2rbox-mmrotate#18]
Excuse me, what is the extraction code of the SSDD dataset? Thanks

**Comment by yangxue0827** [comment]
0518

https://github.com/yangxue0827/h2rbox-mmrotate/tree/main/tools/data/ssdd

<img width="572" alt="image" src="https://github.com/yangxue0827/h2rbox-mmrotate/assets/29257168/65c9723a-4bb5-4e29-a9af-c23e9354ce6c">
