### ISSUE TITLE
About training on HRSID

### ISSUE THREAD

**Issue by Kevinskr** [yangxue0827/h2rbox-mmrotate#19]
Can you give your config file and results on the HRSID dataset?
I trained on HRSID but the result looks bad.

**Comment by yangxue0827** [comment]
We have the same experimental conclusion. We find that H2RBox is not friendly to small-scale datasets, and it is recommended to use [H2RBox-v2](https://github.com/open-mmlab/mmrotate/tree/1.x/configs/h2rbox_v2).

**Comment by Kevinskr** [comment]
> We have the same experimental conclusion. We find that H2RBox is not friendly to small-scale datasets, and it is recommended to use [H2RBox-v2](https://github.com/open-mmlab/mmrotate/tree/1.x/configs/h2rbox_v2).

Thank you for your timely reply
