### ISSUE TITLE
.txt format annotation of horizontal boxes for ssdd and hrsid datasets on h2rbox?

### ISSUE THREAD

**Issue by douling843** [yangxue0827/h2rbox-mmrotate#5]
我已经关注到你在h2rbox上做的关于ssdd和hrsid数据集上的信息，请问，你能给我一份这两个数据集的水平框的标注信息吗？原始的是.xml的格式的，我们也需要.txt格式的标注的信息在h2rbox上运行.

**Comment by yangxue0827** [comment]
SSDD和HRSID的SARWSOODDataset的类是继承自DOTA的DOTAWSOODDataset：
https://github.com/yangxue0827/h2rbox-mmrotate/blob/1dcabfe39c9fdfa5a5704ff6cd97b244b64660d3/h2rbox/dataset.py#L244-L251

因此这里直接加载的SSDD旋转标注，然后送网络之前会转成它的水平外接矩形：
https://github.com/yangxue0827/h2rbox-mmrotate/blob/1dcabfe39c9fdfa5a5704ff6cd97b244b64660d3/h2rbox/dataset.py#L104-L106

**Comment by yangxue0827** [comment]
这个repo已经支持这两个数据集训练了，你只需要去https://github.com/yangxue0827/h2rbox-mmrotate/tree/main/tools/data 下载数据即可，我们都已经处理成能用的格式了。

**Comment by yangxue0827** [comment]
https://github.com/yangxue0827/h2rbox-mmrotate/tree/main/configs/h2rbox
这里给了相关训练的配置文件

**Comment by douling843** [comment]
感谢你的详细解答，以前也在微信群问过好多问题，感谢每次的详细答复！按照旋转标注转成的水平外接矩形去监督得到的旋转框要比水平框标注转成的旋转框精度高，因为没有误差缩放。

![20230208152217](https://user-images.githubusercontent.com/48042521/217462210-feb768b9-0759-4b6f-b680-3a6e1b917276.png)

**Comment by yangxue0827** [comment]
这也是没办法，因为这些数据集（DOTA、HRSID）等好像没有提供水平标注。所以我在文中还用了DIOR-R来验证，因为这个数据集旋转框和水平框标注都有，代码直接加载的水平框标注，就没有转水平外接矩形这个操作。

**Comment by douling843** [comment]
大佬，我看了你的在ssdd上的训练日志，确实很高，我按照你的代码在ssdd上重新跑了几次，180个epoch，在all测试集上都是在第10个epoch达到最好0.55左右，后面震荡的还比较厉害，不稳定，在inshore上只有0.15左右，不知道你当时是否遇到过这种情况，以下是我的训练日志，不知道你是否有什么解决的技巧或者参数上具体的调整，能否告知一下？
[20230209_065055.log](https://github.com/yangxue0827/h2rbox-mmrotate/files/10703435/20230209_065055.log)

**Comment by yangxue0827** [comment]
我看了你的日志，你测试的是inshore+offshore的总体性能，你有单独测试这两个指标，分别是多少？

**Comment by yangxue0827** [comment]
我看你`samples_per_gpu=4`，我的是2，一般来说batch size增加要把学习率也提高相应倍数。我不确定这个是不是这个问题。我建议你先严格按照我的配置文件复现出性能，这样方便排查是否是你改了某些不起眼的参数造成的，或者是环境不一致导致的。

**Comment by yangxue0827** [comment]
因为我看你10epoch的时候到达0.55，看起来是正常的，后面开始震荡，说明开始不收敛了，可能就是你batch size增大了的原因。

**Comment by douling843** [comment]
大佬，这几天一直在按照你的训练日志配环境，确实跑出来好点的结果了，想等到有结果了再回复你。 
inshore：
class | gts | dets | recall | ap    |
+-------+-----+------+--------+-------+
| ship  | 131 | 156  | 0.718  | 0.645 |
+-------+-----+------+--------+-------+
| mAP   |     |      |        | 0.645 
offshore：
+-------+-----+------+--------+-------+
| class | gts | dets | recall | ap    |
+-------+-----+------+--------+-------+
| ship  | 401 | 415  | 0.888  | 0.813 |
+-------+-----+------+--------+-------+
| mAP   |     |      |        | 0.813 |
+-------+-----+------+--------+-------+
还是达不到你的offshore：89.5，我看你回复别人的是可能评价标准不一样会影响结果，请问你是用的07还是12指标？

**Comment by yangxue0827** [comment]
用的默认的07 metric，你用的几卡跑的，我是单卡跑的。

**Comment by douling843** [comment]
谢谢大佬，我用的也是单卡，跑出来了，结果变动很大，我跑了一次用offshore评估的，所以环境配对很重要，现在跑到46epoch时已经达到mAP: 0.8992。
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 193/193, 29.5 task/s, elapsed: 7s, ETA:     0s2023-02-12 09:45:17,706 - mmrotate - INFO - 
+-------+-----+------+--------+-------+
| class | gts | dets | recall | ap    |
+-------+-----+------+--------+-------+
| ship  | 401 | 1246 | 0.950  | 0.899 |
+-------+-----+------+--------+-------+
| mAP   |     |      |        | 0.899 |
+-------+-----+------+--------+-------+
2023-02-12 09:45:17,706 - mmrotate - INFO - Exp name: h2rbox_r50_adamw_fpn_15x_ssdd_le90.py
2023-02-12 09:45:17,707 - mmrotate - INFO - Epoch(val) [46][193]        mAP: 0.8992

**Comment by yangxue0827** [comment]
是这样子的，我分析是因为h2rbox本身是弱监督框架训练比较不容易收敛（SGD优化器需要设置很小的初始学习率才能训练起来了），加上SSDD是个小数据集，因此有较大波动。所以我论文里也没有加小数据集的实验，不可靠。

**Comment by douling843** [comment]
是的，好的，谢谢大佬，感谢每次的认真的解答。
