### ISSUE TITLE
H2RBoxHead' object has no attribute 'seprate_angle'

### ISSUE THREAD

**Issue by Fun772283153** [yangxue0827/h2rbox-mmrotate#8]
**Describe the bug**
H2RBoxHead' object has no attribute 'seprate_angle'

**Reproduction**

```none
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=1 \
    ./tools/train.py  configs/h2rbox/h2rbox_r50_fpn_1x_dota_le90.py\
    --launcher pytorch \
    --work-dir ./output \
```
**Bug fix**
The RotatedFCOSHead has attribute 'separate_angle' not 'seprate_angle' , it seems that you have spelt it wrong.

**Comment by Ririyaa** [comment]
... It's a long story.
